---
services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=${PUID}
      - PGID=${GUID}
      - TZ=Asia/Kolkata
      - TORRENTING_PORT=${TORRENTING_PORT}
    volumes:
      - ${CONFIG}:/config
      - ${DOWNLOADS}:/downloads #optional
    ports:
      - 8081:8080
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
