---
services:
  trends:
    image: trends:0.1.8
    ports:
      - 5001:5001
    container_name: trends
    # networks:
    #   - dashboard
    volumes:
      - ${TRENDS_DATA}:/app/data
    restart: unless-stopped