services:
  homepage:
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 128M
    profiles: ["home"]
    image: ${HOMEPAGE_IMAGE}
    container_name: homepage
    environment:
      PUID: ${PUID}
      PGID: ${GUID}
    ports:
      - 3001:3000
    volumes:
      - ${HOMEPAGE_CONFIG}:/app/config
      - ${EXTERNAL_DRIVE_1}:/disk0
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
