---
services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    volumes:
      - ${WIREGUARD_CONFIG}:/gluetun/wireguard/wg0.conf
    environment:
      - VPN_SERVICE_PROVIDER=custom
      - VPN_TYPE=wireguard
    ports:
      - 8081:8080 # Exposing qBittorrent through Docker Host LAN IP
      - 9696:9696 # Exposing prowlarr
      - 7878:7878 # Exposing radarr
      # - 3001:3001 # Exposing firefox
      # - 5002:3000 # Exposing firefox
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent-vpn
    environment:
      - PUID=${PUID}
      - PGID=${GUID}
      - TZ=Asia/Kolkata
      - TORRENTING_PORT=${TORRENTING_PORT}
    volumes:
      - ${CONFIG}:/config
      - ${DOWNLOADS}:/downloads #optional
    security_opt:
      - no-new-privileges:true
    network_mode: "service:gluetun"
    restart: unless-stopped
